### ISSUE TITLE
[hi]

### ISSUE THREAD

**Issue by chtld** [matteopolleschi/Mixed-implicit-explicit-peridynamic-code#1]
Could you send your presentation and other files to me. Many thanks.
email: zhangshangyuan1357@gmail.com

**Comment by matteopolleschi** [comment]
Hello!
I am sorry, it will take some time as it is now dispersed on some old hard
drive...

Il giorno mer 20 nov 2019 alle ore 02:30 chtld <notifications@github.com>
ha scritto:

**Comment by chtld** [comment]
Thank you very much for your reply.
